AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  TestFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.handler_name
      Runtime: python3.6
      Environment:
        Variables: 
          S3_BUCKET: mamansoft-aws-sam-api-sample
