AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  TestFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: aws_sam_sample.app.main
      Runtime: python3.6
      CodeUri: dist
      Environment:
        Variables:
          S3_BUCKET: mamansoft-aws-sam-api-sample
          RDS_HOST: rds-sample
      Events:
        CreateProduct:
          Type: Api
          Properties:
            Path: /member/{id}
            Method: get
