AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  MemberFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: aws_sam_sample.controller.member
      Runtime: python3.6
      CodeUri: dist
      Environment:
        # TODO...
        Variables:
          RDS_HOST: rds-sample
          S3_ENDPOINT: http://127.0.0.1:8000,
          BUCKET: mamansoft-accounts
      Events:
        CreateProduct:
          Type: Api
          Properties:
            Path: /member/{id}
            Method: get
  AccountFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: aws_sam_sample.controller.account
      Runtime: python3.6
      CodeUri: dist
      Environment:
        # TODO...
        Variables:
          RDS_HOST: rds-sample
          S3_ENDPOINT: http://127.0.0.1:8000,
          BUCKET: mamansoft-accounts
      Events:
        CreateProduct:
          Type: Api
          Properties:
            Path: /account/{name}
            Method: get
